-- 1. Створення таблиці
CREATE TABLE IF NOT EXISTS user_deleted(
	id				UUID			NOT NULL,
	user_id			UUID			NOT NULL,
	login			VARCHAR(550)	NOT NULL,
	login_type		VARCHAR(50)		NOT NULL,
	country_code	VARCHAR(50)		NULL,
	email_domain	VARCHAR(50)		NULL,
	reason			TEXT			NULL,
	restore_until	TIMESTAMPTZ		NOT NULL,
	restored_at		TIMESTAMPTZ		NULL,
	status			VARCHAR(50)		NOT NULL,
	updated_at		TIMESTAMPTZ		NULL,
	created_at		TIMESTAMPTZ		NOT NULL,

	CONSTRAINT pk_user_deleted PRIMARY KEY (id),

	CONSTRAINT fk_user_deleted_user_id
	FOREIGN KEY (user_id)
	REFERENCES user_account(id)
	ON DELETE CASCADE
);

-- 2. Створення індексу для швидкого пошуку
CREATE INDEX IF NOT EXISTS idx_user_deleted_user_id
ON user_deleted (user_id);